### ISSUE TITLE
Executable bit

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/HeroesDataParser#58]
If you have control over file permissions in the released and artifact versions, any chance you could spawn `heroesdata` with +x? It's nitpicky but it requires an intervention script in the workflow I'm setting up.

**Comment by koliva8245** [comment]
Not at this time. You just have to set the permission via chmod.

**Comment by MGatner** [comment]
Yeah that's what I've been doing. As if it heard us, now the Artifacts are downloading without the executable bit on the folder, so the archive isn't even viewable until running `chmod` on it, which keeps macOS from auto-extracting it. Anything inconvenience, but maybe something for polish down the road.

**Comment by koliva8245** [comment]
Try the latest build on the dev-ci-cd-win branch.  The archive is now a .tar.gz for macos/linux. Let's see if that does anything.

**Comment by MGatner** [comment]
That worked for the script! The directory still is missing it, which is odd because it only started with 4.3.1

**Comment by koliva8245** [comment]
Nothing I can do about the archive.
