### ISSUE TITLE
Varian Ability Links

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/HeroesDataParser#60]
Varian's level 4 talent `VarianTwinBladesOfFury` links to `VarianTwinBladesofFury` (notice the lowercase *of*) which doesn't exist because of the case difference.

**Comment by koliva8245** [comment]
Actually, if there's a commit that will auto close the issue, then don't manually close the issue.

**Comment by MGatner** [comment]
Ah sorry, didn't know that was a thing. This will happen at release then?

**Comment by koliva8245** [comment]
Yes, but technically when the branch gets merged into master.

**Comment by MGatner** [comment]
Does GitHub do that? Is it triggered by "fixes #____"?

**Comment by koliva8245** [comment]
Yes, https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by MGatner** [comment]
Slick. The more you know :)
