### ISSUE TITLE
Trailing spaces

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/HeroesDataParser#61]
A number of entries in game strings have trailing spaces. We trim these downstream but it might be nice for it to be handled here. This affects a lot of abiltalent descriptions, one abiltalent name (`"GarroshOppressor|GarroshOppressor|Passive|False": "Oppressor "`) and a handful of abiltalent shorts:
* `"ETCMasterySpeedMetal|ETCSpeedMetalTalent|Trait|False": "Move Speed is added to Rockstar "`
* `"JainaHeroicRingOfFrost|JainaRingOfFrost|Heroic|False": "Create a ring that damages and Roots enemies "`
* `"JainaRingOfFrost|JainaRingOfFrost|Heroic|False": "Create a ring that damages and Roots enemies "`
* `"WitchDoctorHeroicAbilityRavenousSpirits|WitchDoctorRavenousSpirit|Heroic|False": "Channel a damaging, movable spirit "`
* `"WitchDoctorRavenousSpirit|WitchDoctorRavenousSpirit|Heroic|False": "Channel a damaging, movable spirit "`

**Comment by koliva8245** [comment]
I knew about it, but I kinda didn't want to trim the spaces. Blame blizzard for leaving trailing spaces.

**Comment by MGatner** [comment]
Blamed! Thanks for the response.
