### ISSUE TITLE
Dehaka Trait abilityLinks

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/HeroesDataParser#62]
Dehaka seems to be missing abilityLinks for all talents related to his trait. E.g.:
* `DehakaEssenceCollectionTalentTissueRegeneration`
* `DehakaEssenceCollectionOneWhoCollectsTalent`

**Comment by koliva8245** [comment]
Fixed and looks like you missed some.
- `DehakaEssenceCollectionTalentHeroStalker`
- `DehakaPrimalRage`
- `DehakaEssenceClaws`
- `SamuroThreeBladeStyle`

**Comment by MGatner** [comment]
I still don't see them, but maybe `heroes-data` hasn't been updated yet? I'll try running this through at lunch. Currently:
```

        {
          "nameId": "DehakaEssenceCollectionTalentTissueRegeneration",
          "buttonId": "DehakaEssenceCollectionTalentTissueRegeneration",
          "icon": "storm_ui_icon_dehaka_essencecollection.png",
          "charges": {
            "countMax": 50,
            "recastCooldown": 1.0
          },
          "abilityType": "Trait",
          "isQuest": true,
          "sort": 2
        },
```

**Comment by koliva8245** [comment]
The latest version, 76893, on `heroes-data` is wrong. My bad.

**Comment by MGatner** [comment]
No worries! Good chance for me to try a PR.
