### ISSUE TITLE
Indestructible

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/HeroesDataParser#63]
Johanna's "Indestructible" level 20 lost it's cooldown. Talk about overpowered!

`CrusaderHeroicMasteryIndestructable|CrusaderIndestructableTalent|Passive|False`

**Comment by koliva8245** [comment]
Alright, this is my fault.

https://github.com/HeroesToolChest/HeroesDataParser/blob/59477ad40ef5b34277be735df903e776938be9e0/HeroesData.Parser/XmlData/TalentData.cs#L51-L57

**Comment by MGatner** [comment]
Gosh, looking at that now I'm wondering about things like `AnduinBlessedRecovery`. It looks like **heroes-talents** hasn't ever had a CD for them, but maybe it should?

**Comment by koliva8245** [comment]
If it shows up in-game then yes.

**Comment by koliva8245** [comment]
Actually this is not problem. Indestructible and Blessed Recovery do not have cooldowns on their talents.
