### ISSUE TITLE
Traits, cooldowns, and hotkeys

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/HeroesDataParser#64]
Currently (as far as I can tell) there isn't a definitive way to determine if a trait has an activatable hotkey. A combination of `isPassive` and `cooldown` seems to cover it partially but (for example) Artanis' trait `ArtanisShieldOverloadDummy` lacks `isPassive`, has a cooldown, but has no active hotkey. Conversely Gazlowe's trait `TinkerDismantleTurret` lacks `isPassive`, has no cooldown but does have an active hotkey. Tychus and Yrel both have traits with passive base abilities and active subAbilites, but all have cooldowns.

Any guidance is welcome.

**Comment by MGatner** [comment]
Other passive traits with cooldowns: Falstad, Varian

Other active traits without cooldowns: Rexxar

**Comment by koliva8245** [comment]
Yeah, there's no current way to tell.  

However, I think I found a way.  I'll add a new property to abilities for the next version.

**Comment by MGatner** [comment]
Fabulous! Thanks for looking into it. I look forward to seeing what you’ve got.

**Comment by koliva8245** [comment]
I add the `isActive` property to abilities. By default, for all abilities its true otherwise when its false, the ability cannot be activated by a hotkey.

**Comment by MGatner** [comment]
Awesome! I look forward to trying it. Just to be super clear... An ability will be `isActive: true` if it has a hotkey, `isPassive: true` if it is a trait *without* a hotkey, and neither otherwise?

**Comment by koliva8245** [comment]
`isActive: true` -> has hotkey.

`isPassive: true` -> still the same before, when true no hotkey (`isActive` in this case should be false). Doesn't have to be a trait. If false, it **may** have a hotkey depending on the `isActive`.
