### ISSUE TITLE
Samuro trait

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/HeroesDataParser#65]
I know you worked on Samuro some in https://github.com/HeroesToolChest/HeroesDataParser/issues/62 and https://github.com/HeroesToolChest/HeroesDataParser/commit/4db81a07acd6c12f1721cbb5941bd4bf511ac629 but he is still missing the active portion of his trait. I see the cooldown and description under in the game strings under `SamuroIllusionMasterImageSelfCast|SamuroAdvancingStrikes|Trait|False` but `SamuroIllusionMasterImageSelfCast` isn't linked in hero data at all.

It case it helps here's the old HDP output:
```
"trait": [
        {
          "nameId": "SamuroIllusionMaster",
          "buttonId": "SamuroAdvancingStrikes",
          "name": "Image Transmission",
          "icon": "storm_ui_icon_samuro_flowingstrikes.png",
          "cooldownTooltip": "Cooldown: 25 seconds",
          "shortTooltip": "Increase Movement Speed when attacking Heroes",
          "fullTooltip": "Activate to switch places with a target Mirror Image, removing most negative effects from Samuro and the Mirror Image.  Advancing Strikes  Basic Attacks against enemy Heroes increase Samuro's Movement Speed by 25% for 2 seconds.",
          "abilityType": "Trait"
        }
      ],
```

**Comment by koliva8245** [comment]
He's not missing anything. `SamuroIllusionMasterImageSelfCast|SamuroAdvancingStrikes|Trait|False` is for the unit `SamuroMirrorImage` found in the unit data.

`SamuroIllusionMaster|SamuroAdvancingStrikes|Trait|False` is the cooldown id.

**Comment by MGatner** [comment]
Ah, I see, the duplicate `nameId` was overwriting it. Thanks for pointing that out.
