### ISSUE TITLE
Question: Is there a JSON schema for the JSON files generated by HDP?

### ISSUE THREAD

**Issue by pastelmind** [HeroesToolChest/HeroesDataParser#74]
I am trying to manually build a JSON schema for `herodata_*.json`. But I suspect it would be quite inaccurate (and inefficient!)

Is there a JSON schema for the JSON files generated by HDP? If not, is it possible to generate it from the C# model classes, or through some other means?

**Comment by MGatner** [comment]
You want to check out These repos:

* HeroesToolChest/heroes-data
* heroespatchnotes/heroes-talents
* MGatner/heroes-convert

**Comment by pastelmind** [comment]
@MGatner I checked out [HeroesToolChest/heroes-data](/HeroesToolChest/heroes-data) and [heroespatchnotes/heroes-talents](/heroespatchnotes/heroes-talents), but no JSON schemas, I'm afraid. I don't know how to set up a C# build environment, or let alone generate JSON schema from a C# class. My best bet for now is to manually write a schema by examining the output JSON and the model classes.

**Comment by koliva8245** [comment]
No there isn't one. You'll either have to examine the json files or read through the [source code](https://github.com/HeroesToolChest/HeroesDataParser/blob/master/HeroesData.Writer/Writers/HeroData/HeroDataJsonWriter.cs) that generates it or the [source code](https://github.com/HeroesToolChest/Heroes.Icons/blob/6bb0e9cc335ecec184024d52f944266c4065f7cd/Heroes.Icons/DataDocument/HeroDataDocument.cs#L771) that parses the json.

**Comment by pastelmind** [comment]
@koliva8245 I wrote a JSON schema for the JSON file generated by HeroesDataParser.

By the way, I noticed that the [JSON file](https://gist.github.com/pastelmind/2c68fed4d748bfdad309e084ce46fa94) generated with HeroDataParser differs from the [`herodata_80702_localized.json`](https://github.com/HeroesToolChest/heroes-data/blob/master/heroesdata/2.51.1.80702/data/herodata_80702_localized.json) available in [HeroesToolChest/heroes-data](/HeroesToolChest/heroes-data). Why is that?

I used `heroesdata.exe <HotS install path> --json -o . extract` to generate the JSON file. Do you use different CLI args?

**Comment by koliva8245** [comment]
Yes, the json files have been localized.

The following was used
```
'Path/To/Game' --extract-data all --extract-images all --localization all --localized-text`
```
