### ISSUE TITLE
Heroes Identifier in TalentBuilds.txt

### ISSUE THREAD

**Issue by Schtenk** [HeroesToolChest/HeroesDataParser#75]
Sorry if this is not the right place to ask this but do you know anything about the (hex?) identifier specific for every hero at the end of each row in TalentBuilds.txt and if they are present anywhere else in the data.

Some Examples:
Alarak=Build1|01040202010102|01010202010102|01040202010404|F985B31D7FABEB
LiLi=Build1|""|""|""|C9BC9E3413AF26
Hogger=Build1|01010101010101|""|""|B2772400A12093

If you know anything about these and if they could be added to the result from this utility, any info is highly appreciated.
Thanks in advance.

**Comment by koliva8245** [comment]
It's not in the data. I have idea how the identifier is being generated.

**Comment by Schtenk** [comment]
alright, thanks for the quick answer.
