### ISSUE TITLE
$ to briong this up to current

### ISSUE THREAD

**Issue by Br1ghtw1ng** [HeroesToolChest/HeroesDataParser#78]
I want to be fair and reasonable, but i am willing to pay money to bring this and HeroesMatchtracker to update to a working version/state. I am also willing to understand afterward how to maintain it moving forward. I am not a coder, but I am a HOTS lover. please respond if even interesting in keeping this great game alive

**Comment by koliva8245** [comment]
This project is already up to date, as for Heroes Match Tracker, I may work on creating a new version in the far future. Money is not a concern, but rather my lack of motivation and time.
